#ifndef IO_RESERVA_H
#define IO_RESERVA_H


#define GPIO_OVERFLOW 31
#define GPIO_OVERFLOW_BITS 1

#define GPIO_HELLO_WORLD  2
#define GPIO_HELLO_WORLD_BITS  8

#define JUEGO 16
#define JUEGO_BITS 8

#define GPIO_SERIE_ERROR 30
#define GPIO_SERIE_ERROR_BITS 1

#endif
